<script src="../assets/js/jquery-3.2.1.min.js"></script> 
<!-- <script>    
    var btn = document.getElementById("btn-modal");
    var close = document.getElementById("box-modal");
    var modal = document.getElementById("modal"); 
    var modalcontent = document.getElementById("modal-content"); 

    btn.onclick = function() {
        modal.style.display = "block";
    }
    close.onclick = function() {
        window.location.href = "mosaic.php";
    }
    window.onclick = function(event) {
        if (event.target == modalcontent) {
            window.location.href = "mosaic.php";
        }
}
</script> -->